xixi's first commit
xixi121/scu_quarter1 pull request #1
Opened 2022-04-10 19:05 UTC by xixi121

Need code review please

2022-04-11 01:13 UTC, seanxwjiang requested changes

2022-04-11 01:13 UTC, seanxwjiang commented on coen283_os/OSweek1(Xi Liu).cpp
> +	int minbt=kDefaultEndTimeBeyondAllProcesses;
rename to `min_burst_time`

2022-04-11 01:13 UTC, seanxwjiang commented on coen283_os/OSweek1(Xi Liu).cpp
> +//  Finds the first process in the queue at a spesific time and start running it.
You are not running any process, here it just calculates the complete time

2022-04-11 01:13 UTC, seanxwjiang commented on coen283_os/OSweek1(Xi Liu).cpp
> +		res=FindFirstInReadyQueue(processes, time+1);
If the arrival time of the next ready-process is too far away, you excessively calls this function recursively here. This is not a right behavior.
This can be solved by either changing the vector<Process> to priority_queue<Process>, or recording the the min_arrival_time in the for-loop above (i.e. line 40)

2022-04-11 01:13 UTC, seanxwjiang commented on coen283_os/OSweek1(Xi Liu).cpp
> +	float sum_turn_around_time=0;
usually we don't use float unless this is a memory-sensitive program. Just using `double` here

2022-04-16 03:46 UTC, xixi121 commented on coen283_os/OSweek1(Xi Liu).cpp
> +	int minbt=kDefaultEndTimeBeyondAllProcesses;
o

2022-04-16 03:46 UTC, xixi121 commented on coen283_os/OSweek1(Xi Liu).cpp
> +//  Finds the first process in the queue at a spesific time and start running it.
thinking

2022-04-16 03:47 UTC, xixi121 commented on coen283_os/OSweek1(Xi Liu).cpp
> +		if(processes[i].arrival_time<=time){
o

2022-08-19 21:33 UTC, merged